---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
#  amd64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
#  armhf: ghcr.io/home-assistant/aarch64-base-debian:bookworm
#  armv7: ghcr.io/home-assistant/aarch64-base-debian:bookworm
#  i386: ghcr.io/home-assistant/aarch64-base-debian:bookworm
codenotary:
  signer: dan.veitch@gmail.com
  base_image: codenotary@frenck.dev
