---
name: pi.alert
description: Network Intrusion Monitor, from Pi.Alert.
slug: addon_pi.alert
version: 0.0.1
webui: [PROTO]://[HOST]:[PORT:80]
host_network: true
startup: services
arch:
#  - armhf
#  - armv7
  - aarch64
#  - amd64
#  - i386
map:
  - share:rw
init: false
ports:
  80/tcp: 8078
ports_description:
  80/tcp: "Web entrance"
options:
  debug: false
  ssl: false
schema:
  debug: bool
  ssl: bool
url: https://github.com/danveitch76/hassio-addons/tree/master/pi.alert
image: ghcr.io/danveitch76/{arch}-addon-pi.alert
homeassistant: 2023.12.0
