#!/command/with-contenv bash

if [ "${PH_VERBOSE:-0}" -gt 0 ] ; then
    set -x ;
fi

if [[ 1 -eq ${WEBLOGS_STDOUT:-0} ]]; then
  #lighthttpd cannot use /dev/stdout https://redmine.lighttpd.net/issues/2731
  for fi in /root/pialert/log/access-pialert.log /root/pialert/log/error-pialert.log
  do
    if [[ ! -p ${fi} ]]; then
      rm -f ${fi}
      mkfifo -m 600 ${fi}
    fi
  done
  chown -R www-data:www-data /var/log/lighttpd
  service lighttpd-access-log start
  service lighttpd-error-log start
  sleep 2
else
  #remove fifo if exists
  [[ -p /root/pialert/log/access-pialert.log ]] && rm -Rf /root/pialert/log/access-pialert.log
  [[ -p  /root/pialert/log/error-pialert.log ]] && rm -Rf /root/pialert/log/error-pialert.log

  # install /dev/null log files to ensure they exist (create if non-existing, preserve if existing)
  [[ ! -f /root/pialert/log/access-pialert.log ]] && install /dev/null /root/pialert/log/access-pialert.log
  [[ ! -f  /root/pialert/log/error-pialert.log ]] && install /dev/null /root/pialert/log/error-pialert.log

  # Ensure that permissions are set so that lighttpd can write to the logs
  chown -R www-data:www-data /var/log/lighttpd
  chmod 0644 /root/pialert/log/access-pialert.log /root/pialert/log/error-pialert.log
fi

lighttpd -D -f /etc/lighttpd/lighttpd.conf
