---
name: Pi.Alert
description: Network Intrusion Monitor, from Pi.Alert.
slug: pialert_addon
version: 0.0.11
webui: http://[HOST]:[PORT:8078]
host_network: true
startup: services
arch:
#  - armhf
#  - armv7
  - aarch64
#  - amd64
#  - i386
map:
  - addon_config:rw
init: false
ports:
  8078/tcp: 8078
ports_description:
  8078/tcp: "Web entrance"
options:
  accept_eula: false
  accept_rgpd: false
schema:
  accept_eula: bool
  accept_rgpd: bool
url: https://github.com/danveitch76/hassio-addons/tree/master/pialert
image: ghcr.io/danveitch76/{arch}-addon-pialert
homeassistant: 2024.12.0
